"""Data API stubs: in a real system this would fetch historical/real-time data."""

from __future__ import annotations

from pathlib import Path
from typing import List, Optional

import pandas as pd
import yfinance as yf

DATA_DIR = Path("data")

class MarketDataAPI:
    """ Simple daily price data loader using yfinance + local CSV cache.

    - Caches each symbol as data/<SYMBOL>.csv
    - Auto-adjusts for dividends/splits
    - Provides:
        * get_history() for one symbol
        * get_latest_price() for one symbol
        * get_prices_for_universe() for multiple symbols
        * get_return_series() for daily returns
    """
    def __init__(self, data_dir: Optional[Path] = None):
        self.data_dir = data_dir or DATA_DIR
        self.data_dir.mkdir(parents=True, exist_ok=True)

# internal processer,for #

    def _cache_path(self, symbol: str) -> Path:
        return self.data_dir / f"{symbol}.csv"

    def _download_and_cache(
            self,
            symbol: str,
            start: str = "2000-01-01",
            end: Optional[str] = None,
    ) -> pd.DataFrame:
        """
        Download from yfinance and save to CSV.
        Auto-adjust prices.
        """
        df = yf.download(symbol, start=start, end=end, auto_adjust=True)
        if df.empty:
            raise ValueError(f"No data returned from yfinance for symbol {symbol}")
        df.to_csv(self._cache_path(symbol))
        return df

# public API connection

    def get_history(
            self,
            symbol: str,
            start: str = "2000-01-01",
            end: Optional[str] = None,
    ) -> pd.DataFrame:
        """Get historical price data for a symbol as a DataFrame."""
        cache_path = self._cache_path(symbol)
        if cache_path.exists():
            # Handle yfinance multi-level header CSVs (generated by recent versions)
            # We first peek to see if it's the complex format
            with open(cache_path, 'r') as f:
                first_lines = [next(f) for _ in range(3)]
            
            if "Ticker" in first_lines[1] and "Date" in first_lines[2]:
                # It's the multi-index format: Skip first 3 rows, use row 0's names but we need to map them manually 
                # or just read from line 4 and assume standard order? 
                # Use header=0 (Price, Close...), skip rows 1 and 2?
                # Actually safest is to read, check for non-numeric, and clean.
                df = pd.read_csv(cache_path, index_col=0, parse_dates=True)
                
                # Check if first few rows are metadata (strings in numeric cols)
                # If the index name is 'Date', but the first index value is NaN or 'Date' or empty
                if isinstance(df.index, pd.DatetimeIndex) == False:
                     # Try reloading skipping bad rows if index isn't dates
                     pass

                # Force convert to numeric, coercing errors (like 'SPY' in Close col) to NaN
                cols = df.columns
                df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')
                df = df.dropna()
            else:
                df = pd.read_csv(cache_path, index_col=0, parse_dates=True)

            # Ensure index is a DatetimeIndex even if parse failed; coerce bad values
            df.index = pd.to_datetime(df.index, errors="coerce")
            # drop rows where the index couldn't be parsed
            df = df[~df.index.isna()]
        else:
            df = self._download_and_cache(symbol, start, end)
        if end:
            df = df[df.index <= pd.to_datetime(end)]
        if start:
            df = df[df.index >= pd.to_datetime(start)]
        return df

    def get_latest_price(self, symbol: str) -> float:
        """
        return the lstest price data for a symbol

        :param symbol:
        :return:
        """
        df = self.get_history(symbol)
        if df.empty:
            raise ValueError(f"No data available for symbol {symbol}")
        return df.iloc[-1]["Close"]

    def get_prices_for_universe(
            self,
            symbols: List[str],
            start: str = "2000-01-01",
            end: Optional[str] = None,
    ) -> pd.DataFrame:
        """Return a DataFrame of Close prices for `symbols`.

        Index: DatetimeIndex
        Columns: symbols (e.g. "SPY")

        Uses the local CSV cache if available (via `get_history`).
        Missing values are forward/backfilled.
        """
        frames = []
        for sym in symbols:
            try:
                df = self.get_history(sym, start=start, end=end)
            except Exception:
                # Try to download if cache/read fails
                df = self._download_and_cache(sym, start=start, end=end)

            # prefer 'Close' column; yfinance with auto_adjust keeps 'Close' adjusted
            if "Close" in df.columns:
                col = "Close"
            elif "Adj Close" in df.columns:
                col = "Adj Close"
            else:
                col = df.columns[-1]

            ser = df[[col]].rename(columns={col: sym})
            frames.append(ser)

        if not frames:
            return pd.DataFrame()

        out = pd.concat(frames, axis=1).sort_index()
        # Fill small gaps conservatively
        out = out.ffill().bfill()
        return out





